name: Deploy
on:
  push:
jobs:
  push-container:
    name: Push Container
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    with:
      image: rosvik/qr.248.no
      registry_url: cubby.no
      registry_username: rosvik
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  cubbyman-reload:
    name: Cubbyman Reload
    needs: push-container
    uses: rosvik/workflows/.github/workflows/cubbyman-reload.yml@main
    with:
      base_url: https://cubby.no
    secrets:
      credentials: ${{ secrets.CUBBYMAN_CREDENTIALS }}
