name: Push Container To Registry
on:
  push:
    branches:
      - main
      - rosvik/carg-chef

jobs:
  podman-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache Cargo dependencies and target directory
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      # Setup for multi architecture build
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: qr.248.no
          tags: test ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          oci: true
          layers: true
          containerfiles: |
            Containerfile

      - name: Push To cubby.no
        id: push-to-cubby
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: cubby.no/rosvik
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-cubby.outputs.registry-paths }}"
