name: Push Container To Registry
on:
  push:
    branches:
      - main
      - rosvik/carg-chef

jobs:
  podman-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: cubby.no
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Containerfile
          push: true
          registry: cubby.no
          tags: cubby.no/rosvik/qr.248.no:test,cubby.no/rosvik/qr.248.no:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
